social_django/social/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from social.views import inicioView, logoutBaseView, loginBaseView, RegisterView, RegisterCatalogView, \
						RegisterCatalogEditarView, CatalogDeleteView


urlpatterns = [
	path('', inicioView.as_view(), name='inicio'),
	path('register/user/crear', RegisterView.as_view(), name='register_user'),
	path('register/catalog/crear', RegisterCatalogView.as_view(), name='register_catalog'),
	path('register/catalog/<int:id>/editar', RegisterCatalogEditarView.as_view(), name='editar_catalog'),
	path('catalog/<int:id>/delete', CatalogDeleteView.as_view(), name='delete_catalog'),
	path('login/', loginBaseView.as_view(), name='login'),
	path('logout/', logoutBaseView.as_view(), name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_django/social_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social.urls')),
]

social_django/social/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager

class PagesInfo(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre', null=False, blank=False)
    estado_pagina = models.BooleanField(max_length=5, verbose_name='Estado', null=False, blank=False)
    ruta_foto = models.ImageField(upload_to='fotos-paginas', verbose_name='Foto', null=False, blank=False)
    enlace = models.CharField(max_length=100, verbose_name='Enlace', null=True, blank=True)
    descripcion = models.CharField(max_length=500, verbose_name='Descripcion', null=True, blank=True)
    fecha_creacion = models.DateField(verbose_name='Fecha Creacion', null=False, blank=False)

    def __str__(self):
        return self.enlace

    class Meta:
        verbose_name = 'Pagina'
        verbose_name_plural = 'Paginas'

class Usuarios(AbstractBaseUser):
    nombre = models.CharField(max_length=100, verbose_name='Nombre', null=False, blank=False)
    apellido = models.CharField(max_length=100, verbose_name='Apelido', null=False, blank=False)
    ruta_foto = models.ImageField(upload_to='fotos-perfil', verbose_name='Foto', null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación', null=False, blank=False)
    email = models.CharField(max_length=200, verbose_name='Email', null=False, blank=False)
    telefono = models.CharField(max_length=200, verbose_name='Telefono', null=True, blank=True)
    direccion = models.CharField(max_length=200, verbose_name='Direccion', null=True, blank=True)
    observaciones = models.CharField(max_length=200, verbose_name='Observaciones', null=True, blank=True)
    cargo = models.CharField(max_length=200, verbose_name='Observaciones', null=True, blank=True)
    username = models.CharField('Nombre usuario', unique=True, max_length=100)

    USERNAME_FIELD ='useranme'
    REQUIRED_FIELDS = ['email', 'nombre', 'apellido']

    def __str__(self):
        return f'{self.nombre}{self.apellido}'


#user = User.objects.last()
#print(user.id)
#usuarios = Usuarios.objects.create(nombre='', apellido='',ruta_foto='',fecha_creacion='',email='',telefono='',observaciones='')

social_django/social/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()
	password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirma Contraseña', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']
		help_texts = {k:"" for k in fields }

social_django/social/views.py
from concurrent.futures._base import LOGGER
from datetime import datetime
import json
import pytz
from django.db.transaction import atomic, rollback
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.contrib import messages
from django.views import View
from django.contrib.auth import logout, authenticate, login
from social.models import Usuarios
from .response import RespuestaJson
from django.contrib.auth.hashers import make_password, check_password


class inicioView(View):
    def get(self, request):
        data_pages = PagesInfo.objects.all()
        info_team = Usuarios.objects.all()
        usuario_data = ""
        if request.user.is_authenticated:
            usuario_data = Usuarios.objects.get(id=request.user.id)
        return render(request, 'base/base.html', {'data': data_pages, 'usuario': usuario_data, 'team': info_team})


class logoutBaseView(View):
    def get(self, request):
        logout(request)
        info_team = Usuarios.objects.all()
        data_pages = PagesInfo.objects.all()
        messages.success(request, 'Hasta pronto')
        return redirect('/')
        #return render(request, 'base/base.html', {'data': data_pages, 'usuario': None, 'team': info_team})


class loginBaseView(View):

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        data_pages = PagesInfo.objects.all()
        info_team = Usuarios.objects.all()

        if user is not None:
            login(request, user)
            usuario_data = Usuarios.objects.get(id=request.user.id)
            messages.success(request, 'Bienvenido :{0} '.format(usuario_data.username))
            return render(request, 'base/base.html', {'data': data_pages, 'usuario': usuario_data, 'team': info_team})
        else:
            messages.error(request, 'Intente de nuevo. ')
            return render(request, 'base/base.html', {'data': data_pages, 'usuario': None})


class RegisterView(View):

    def get(self, request):
        usuarios = Usuarios.objects.all()
        return render(request, 'base/_modal_crear_editar_usuarios.html', {'data': usuarios})

    def post(self, request):
        data_pages = PagesInfo.objects.all()
        usuarios = Usuarios()
        usuariosModel = User()

        usuarios.nombre = request.POST.get('nombre')
        usuarios.apellido = request.POST.get('apellido')
        usuarios.descripcion = request.POST.get('descripcion')
        usuarios.estado = True
        usuarios.ruta_foto = request.FILES.get('foto', None)
        usuarios.cargo = request.POST.get('cargo')
        usuarios.email = request.POST.get('email')
        usuarios.direccion = request.POST.get('direccion')
        usuarios.telefono = request.POST.get('telefono')
        usuarios.ultimo_ingreso = datetime.now(pytz.utc)
        username = '{}.{}'.format(usuarios.nombre, usuarios.apellido).strip()
        usuariosModel.username = username
        usuariosModel.date_joined = usuarios.ultimo_ingreso
        usuariosModel.first_name = usuarios.nombre
        usuariosModel.last_name = usuarios.apellido
        usuariosModel.last_login = usuarios.ultimo_ingreso
        usuariosModel.is_active = usuarios.estado
        usuariosModel.password = make_password(request.POST.get('password').strip())
        checkpassword = check_password(request.POST['password'], usuariosModel.password)

        if User.objects.filter(username=username).exists():
            info_usuarios = Usuarios.objects.all()
            messages.error(request, 'este nombre de usuario ha sido registrado')
            #return render(request, 'base/base.html', {'data': data_pages, 'usuario': None})
            return RespuestaJson.error("este nombre de usuario ha sido registrado")

        else:
            try:
                with atomic():
                    #usuarios.save()
                    usuariosModel.save()
                    messages.success(request, 'Registro exitoso')
                    return RespuestaJson.exitosa({"catalog_info": "OK"})
            except:
                rollback()
                LOGGER.exception('Falló la creación del registro.')
                messages.success(request, 'Ha ocurrido un error al realizar la acción')
                return RespuestaJson.error('Ha ocurrido un error al realizar la acción')




class RegisterCatalogView(View):

    def get(self, request):
        data_pages = PagesInfo.objects.all()
        return render(request, 'base/_modal_crear_editar_paginas.html', {'data': data_pages})

    def post(self, request):
        paginas = PagesInfo()

        paginas.nombre = request.POST.get('nombre')
        paginas.descripcion = request.POST.get('descripcion')
        paginas.estado_pagina = True
        paginas.enlace = request.POST.get('enlace')
        paginas.fecha_creacion = datetime.now(pytz.utc)
        paginas.ruta_foto = request.FILES.get('imagen', None)
        paginas.editar = True

        if request.is_ajax():

            catalog_info = {
                "nombre": paginas.nombre,
                "descripcion": paginas.descripcion,
                "enlace": paginas.enlace,
                "fecha_creacion": paginas.fecha_creacion,
                "estado_pagina": True,
                "ruta_foto": "portfolio-1.jpg",
            }
            try:
                with atomic():
                    paginas.save()
                    messages.success(request, 'Registro exitoso')
                    return RespuestaJson.exitosa({"catalog_info": catalog_info})
            except:
                rollback()
                LOGGER.exception('Falló la creación del registro.')
                messages.success(request, 'Ha ocurrido un error al realizar la acción')
                return RespuestaJson.error('Ha ocurrido un error al realizar la acción')
        else:
            messages.error(request, 'Ha ocurrido un error al realizar la acción')
            return RespuestaJson.error('Ha ocurrido un error al realizar la acción')


class RegisterCatalogEditarView(View):

    def get(self, request, id):
        data_pages = PagesInfo.objects.get(id=id)
        data_pages.editar = True
        return render(request, 'base/_modal_crear_editar_paginas.html', {'data': data_pages})

    def post(self, request, id):
        paginas = PagesInfo()

        consecutivo_db = PagesInfo.objects.get(id=id)

        paginas.nombre = request.POST.get('nombre')
        paginas.descripcion = request.POST.get('descripcion')
        paginas.estado_pagina = True
        paginas.enlace = request.POST.get('enlace')
        paginas.fecha_creacion = datetime.now(pytz.utc)
        paginas.ruta_foto = request.FILES.get('imagen', None)
        #paginas.ruta_foto = "portfolio-1.jpg"
        paginas.editar = True
        paginas.id = consecutivo_db.id

        if request.is_ajax():
            catalog_info = {
                "nombre": paginas.nombre,
                "descripcion": paginas.descripcion,
                "enlace": paginas.enlace,
                "fecha_creacion": paginas.fecha_creacion,
                "estado_pagina": True,
                "ruta_foto": "portfolio-1.jpg",
                "estado" : "OK"
            }
            try:
                with atomic():
                    paginas.save(update_fields=['nombre', 'descripcion', 'enlace', 'ruta_foto', 'fecha_creacion'])
                    messages.success(request, 'Se ha editado: {0}'.format(paginas.nombre))
                    return RespuestaJson.exitosa({"catalog_info": catalog_info})
            except:
                rollback()
                LOGGER.exception('Falló la edición del registro.')
                messages.error(request, 'Ha ocurrido un error al realizar la acción')
                return RespuestaJson.error('Ha ocurrido un error al realizar la acción')

        else:
            messages.error(request, 'Ha ocurrido un error al realizar la acción')
            return RespuestaJson.error('Ha ocurrido un error al realizar la acción')


class CatalogDeleteView(View):

    def post(self, request, id):
        info_pages = PagesInfo.objects.get(id=id)
        body_unicode = request.body.decode('utf-8')
        datos_registro = json.loads(body_unicode)
        justificacion = datos_registro['justificacion']
        if not info_pages.estado_pagina:
            return RespuestaJson.error("Este registro ya ha sido anulado.")
        try:
            with atomic():
                info_pages.estado_pagina = False
                info_pages.descripcion = justificacion
                info_pages.fecha_creacion = datetime.now(pytz.utc)
                info_pages.save(update_fields=['estado_pagina', 'descripcion', 'fecha_creacion'])
                messages.success(request, 'Registro {0} anulado'.format(info_pages.nombre))
                return RespuestaJson.exitosa()
        except:
            rollback()
            LOGGER.exception('Error anulando el registro')
            return RespuestaJson.error('Ha ocurrido un error al realizar la acción')

social_django/social/templates/sections/about.html
<!-- ======= About Section ======= -->
{% load static %}
<section id="about" class="about section-bg">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>About</h2>
            <h3>Find Out More <span>Acerca de nosotros</span></h3>
            <p>Página diseñada para el curso.</p>
        </div>

        <div class="row">
            <div class="col-lg-6" data-aos="fade-right" data-aos-delay="100">
                <img src="{% static '/assets/img/about.jpg' %}" class="img-fluid" alt="">
            </div>
            <div class="col-lg-6 pt-4 pt-lg-0 content d-flex flex-column justify-content-center" data-aos="fade-up"
                 data-aos-delay="100">
                <h3>Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h3>
                <p class="fst-italic">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore
                    magna aliqua.
                </p>
                <ul>
                    <li>
                        <i class="bx bx-store-alt"></i>
                        <div>
                            <h5>Ullamco laboris nisi ut aliquip consequat</h5>
                            <p>Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade</p>
                        </div>
                    </li>
                    <li>
                        <i class="bx bx-images"></i>
                        <div>
                            <h5>Magnam soluta odio exercitationem reprehenderi</h5>
                            <p>Quo totam dolorum at pariatur aut distinctio dolorum laudantium illo direna pasata
                                redi</p>
                        </div>
                    </li>
                </ul>
                <p>
                    Desarrollo en Django para el curso de python
                </p>
            </div>
        </div>
    </div>
</section><!-- End About Section -->

social_django/social/templates/sections/catalogo.html
{% load static %}
<!-- ======= Portfolio Section ======= -->
<section id="portfolio" class="portfolio">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
            <h2>Cátalogo de páginas</h2>
            <h3>mire <span>Portfolio</span></h3>
            <br>
            {% if perms.social.add_pagesinfo %}
                <a id="crear_{{ catalogo.id }}"
                   href="javascript:abrirModalCrearCatalogo('{% url 'register_catalog' %}')"
                   title="Registrar">
                    <span class="bi bi-plus-circle fw-300"></span>
                </a>
            {% endif %}
            <br>
        </div>
        <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200" id="catalogoCont">
            {% for catalogo in data %}
                {% if catalogo.estado_pagina%}
                    <div class="col-lg-4 col-md-3 portfolio-item filter-app">
                        <img src="{{ catalogo.ruta_foto.url }}" class="img-fluid" alt="">
                        <div class="portfolio-info">
                            <h3>{{ catalogo.nombre }}</h3>
                            <p>{{ catalogo.descripcion }}</p>
                            <a href="{{ catalogo.ruta_foto.url }}" data-gallery="portfolioGallery"
                               class="portfolio-lightbox preview-link" title={{ catalogo.descripcion }}>
                                <i class="bx bx-plus"></i></a>
                            <a href="{{ catalogo.enlace }}" class="details-link" title="More Details"
                               target="_blank">
                                <i class="bx bx-link"></i>
                            </a>
                            {% if perms.social.add_pagesinfo %}
                                <a id="editar_{{ catalogo.id }}" href="javascript:abrirModalCrearCatalogo('{% url 'editar_catalog' catalogo.id%}')" data-original-title="Editar">
                                    <i class="bi bi-pencil-square"></i>
                                </a>
                            {% endif %}
                            {% if perms.social.delete_pagesinfo %}
                                <a id="eliminar_{{ catalogo.id }}" href="javascript:void(0);"  onclick="fConfirmarEliminar({{ catalogo.id }}, true)" data-original-title="Eliminar">
                                    <i class="bi bi-trash"></i>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</section><!-- End Portfolio Section -->

<div class="modal fade" id="_crearEditar" tabindex="-1" aria-labelledby="editar" aria-hidden="true"></div>

social_django/social/templates/sections/footer.html
<!-- ======= Footer ======= -->
<footer id="footer">

    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6 footer-contact">
                    <h3>BizLand<span>.</span></h3>
                    <p>
                        A108 Adam Street <br>
                        New York, NY 535022<br>
                        United States <br><br>
                        <strong>Phone:</strong> +1 5589 55488 55<br>
                        <strong>Email:</strong> info@example.com<br>
                    </p>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Our Social Networks</h4>
                    <p>Cras fermentum odio eu feugiat lide par naso tierra videa magna derita valies</p>
                    <div class="social-links mt-3">
                        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="container py-4">
        <div class="copyright">
            &copy; Copyright <strong><span>BizLand</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bizland-bootstrap-business-template/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </div>
</footer><!-- End Footer -->

social_django/social/templates/sections/header.html
<!-- ======= Header ======= -->
<header id="header" class="d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">
        <div class="col-lg-8">
            <h1 class="logo"><a href={% url 'inicio'%}>Django<span>.</span></a></h1>
        </div>
        <div class="col-md-4">
            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" href="{% url 'inicio' %}">Home</a></li>
                    <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#team">Nuestro equipo</a></li>
                    <li class="dropdown"><a href="#"><span>Usuario</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            {% if request.user.is_authenticated %}
                                <li><a href="#perfil">Perfil</a></li>
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                            {% else %}
                                <li>
                                    <a href="#" data-bs-toggle="modal" data-bs-target="#loginModal"
                                       data-bs-whatever="@mdo">Login
                                    </a>
                                </li>
                            {% endif %}

                            <li><a href="#registro">Registrar Usuario</a></li>
                        </ul>
                    </li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
        </div>

    </div>
</header><!-- End Header -->

social_django/social/templates/sections/perfil.html
{% load static %}
<!-- ======= Contact Section ======= -->
<section id="perfil" class="perfil contact">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>Perfil de usuario</h2>
            <h3><span>Datos de contacto</span></h3>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-4">
                <div class="member-img">
                    <img src="{{usuario.ruta_foto.url}}" class="img-fluid" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="row">

                    <div class="col-lg-6">
                        <div class="info-box my-0">
                            <i class="bx bx-user"></i>
                            {% if usuario.nombre %}
                                <h3>{{usuario.usuario}}</h3>
                            {% endif %}
                            <p>{{usuario.nombre}} {{usuario.apellido}}</p>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="info-box my-0">
                            <i class="bx bx-map"></i>
                            <h3>Dirección</h3>
                            <p>{{usuario.direccion}}</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="info-box  my-0">
                            <i class="bx bx-envelope"></i>
                            <h3>Email</h3>
                            <p>{{usuario.email}}</p>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="info-box  my-0">
                            <i class="bx bx-phone-call"></i>
                            <h3>Teléfono</h3>
                            <p>{{usuario.telefono}}</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="info-box my-0">
                            <i class="bx bx-user-voice"></i>
                            <h3>Redes Sociales</h3>
                            <div class="social">
                                <a href="https://twitter.com" target="_blank"><i class="bi bi-twitter"></i></a>
                                <a href="https://www.facebook.com/" target="_blank"><i class="bi bi-facebook"></i></a>
                                <a href="https://www.instagram.com" target="_blank"><i class="bi bi-instagram"></i></a>
                                <a href="https://www.linkedin.com/" target="_blank"><i class="bi bi-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</section><!-- End Contact Section -->

social_django/social/templates/sections/register.html
<!-- ======= Contact Section ======= -->
<section id="registro" class="contact">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
            <h2>Registrar</h2>
            <h3><span>Registro de usuarios</span></h3>
            <div class="row" data-aos="fade-up" data-aos-delay="100">

                    <a id="crear_{{ catalogo.id }}"
                       href="javascript:abrirModalCrearUsuarios('{% url 'register_user' %}')"
                       title="Registrar">
                        <span class="bi bi-plus-circle fw-300"></span>
                    </a>

            </div>
        </div>
    </div>
</section>

social_django/social/templates/sections/team.html
<!-- ======= Team Section ======= -->
{% load static %}
<section id="team" class="team section-bg">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>Equipo</h2>
            <h3>Nuestro equipo de trabajo <span>Team</span></h3>
            <p>Equipo desarrollador de la página.</p>
        </div>
        <div class="row">
            {% for equipo in team %}
            <div class="col-lg-3 col-md-6 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
                <div class="member">
                    <div class="member-img">
                         <img src="{{ equipo.ruta_foto.url}}" class="img-fluid" alt="">
                        <div class="social">
                            <a href="https://twitter.com" target="_blank"><i class="bi bi-twitter"></i></a>
                            <a href="https://www.facebook.com/" target="_blank"><i class="bi bi-facebook"></i></a>
                            <a href="https://www.instagram.com" target="_blank"><i class="bi bi-instagram"></i></a>
                            <a href="https://www.linkedin.com/" target="_blank"><i class="bi bi-linkedin"></i></a>
                        </div>
                    </div>
                    <div class="member-info">
                        <h4>{{equipo.nombre}} {{equipo.apellido}}</h4>
                        <span>{{equipo.cargo}}</span>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</section><!-- End Team Section -->

social_django/social/templates/sections/topbar.html
<section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
        <div class="contact-info d-flex align-items-center">
            <i class="bi bi-envelope d-flex align-items-center"><a
                    href="mailto:contact@example.com">contact@example.com</a></i>
            <i class="bi bi-phone d-flex align-items-center ms-4"><span>+1 5589 55488 55</span></i>
        </div>
        <div class="social-links d-none d-md-flex align-items-center">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
        </div>
    </div>
</section>